version: "3"

services:

  mysql: 
    image: mysql:8.0.33
    container_name: ${APP_NAME}_mysql_8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DEFAULT_DATABASE}
    volumes:
      - ./db:/var/lib/mysql 

  php:
    build:
        context: .
        dockerfile: docker/php/Dockerfile
    container_name: ${APP_NAME}_php_8
    ports:
        - 8000:8000
    expose:
        - "9003"
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_php_8_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1    
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
